@extends('layouts.guest')

@section('content')
<div class="auth-heading-block"><p class="auth-eyebrow">Choose a new password</p><h1 id="login-heading">Reset your password</h1><p class="auth-intro">Enter the code from your email and create a password with at least 10 characters, uppercase and lowercase letters, a number, and a symbol.</p></div>
@if(session('error'))<div class="auth-alert" role="alert">{{ session('error') }}</div>@endif
@if(session('success'))<div class="auth-success" role="status">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('password.update') }}" class="auth-form" x-data="{ password: '' }">@csrf<div class="auth-field"><label for="code">6-digit code</label><div class="auth-input-wrap"><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required autofocus placeholder="000000" value="{{ old('code') }}"></div>@error('code')<p class="auth-field-error">{{ $message }}</p>@enderror</div><div class="auth-field"><label for="password">New password</label><div class="auth-input-wrap"><input id="password" name="password" type="password" autocomplete="new-password" required minlength="10" x-model="password" placeholder="10+ characters"></div><ul class="mt-2 space-y-1 text-xs text-slate-500"><li :class="password.length >= 10 ? 'text-emerald-700' : ''">At least 10 characters</li><li :class="/[A-Z]/.test(password) ? 'text-emerald-700' : ''">At least one uppercase letter</li><li :class="/[a-z]/.test(password) ? 'text-emerald-700' : ''">At least one lowercase letter</li><li :class="/[0-9]/.test(password) ? 'text-emerald-700' : ''">At least one number</li><li :class="/[^A-Za-z0-9]/.test(password) ? 'text-emerald-700' : ''">At least one symbol</li></ul>@error('password')<p class="auth-field-error">{{ $message }}</p>@enderror</div><div class="auth-field"><label for="password_confirmation">Confirm password</label><div class="auth-input-wrap"><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required minlength="10" placeholder="Enter it again"></div>@error('password_confirmation')<p class="auth-field-error">{{ $message }}</p>@enderror</div><button class="auth-submit" type="submit"><span>Save new password</span></button></form>
<form method="POST" action="{{ route('password.resend') }}" class="mt-4 text-center">@csrf<button class="text-sm font-semibold text-brand-700 hover:text-brand-900" type="submit">Send another code</button></form>
@endsection
